### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [CodoSapiens-HACKNITP/PRECycle#1]
Hi,<br><br>url : https://github.com/CodoSapiens-HACKNITP/PRECycle/blob/b2293a079d9dc97f2f2616ebfa20ba61580f8df7/config/default.json <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by rishabhborn2win** [comment]
Yeah sure!
